"""
Confluence REST API publisher.
Creates a post-mortem page under a configured parent page in a given space.
Uses API token auth (Atlassian Cloud) or Basic Auth (Confluence Server/DC).
"""
from __future__ import annotations

import logging
import os
import json
from datetime import datetime, timezone

import httpx

from models import ConfluenceResult

log = logging.getLogger("rca.confluence_publish")

# ── Config ────────────────────────────────────────────────────────
CONF_BASE_URL       = ""    # e.g. https://yourorg.atlassian.net/wiki
CONF_USERNAME       = ""    # your Atlassian account email
CONF_API_TOKEN      = ""    # API token from id.atlassian.net
CONF_SPACE_KEY      = ""    # e.g. SRE
CONF_PARENT_PAGE_ID = ""    # numeric page ID
CONF_TIMEOUT        = 30


def init_confluence(
    base_url: str,
    username: str,
    api_token: str,
    space_key: str,
    parent_page_id: str,
) -> None:
    global CONF_BASE_URL, CONF_USERNAME, CONF_API_TOKEN, CONF_SPACE_KEY, CONF_PARENT_PAGE_ID
    # Ensure /wiki suffix is present for Atlassian Cloud
    base_url = base_url.rstrip("/")
    if "atlassian.net" in base_url and not base_url.endswith("/wiki"):
        base_url = base_url + "/wiki"
    CONF_BASE_URL = base_url
    CONF_USERNAME       = username
    CONF_API_TOKEN      = api_token
    CONF_SPACE_KEY      = space_key
    CONF_PARENT_PAGE_ID = parent_page_id
    log.info(
        "Confluence client initialised  base=%s  space=%s  parent=%s",
        CONF_BASE_URL, CONF_SPACE_KEY, CONF_PARENT_PAGE_ID,
    )


# ── Helpers ───────────────────────────────────────────────────────
def _auth() -> httpx.BasicAuth:
    return httpx.BasicAuth(CONF_USERNAME, CONF_API_TOKEN)


def _headers() -> dict:
    return {"Accept": "application/json", "Content-Type": "application/json"}


def _build_confluence_storage(
    result: ConfluenceResult,
    incident_id: str,
    severity: str,
    ci: str,
    mttr_minutes: int,
    quality_score: int,
    overall_quality: str,
    opened_at: str,
    closed_at: str,
    team: str,
) -> str:
    """
    Convert ConfluenceResult into Confluence Storage Format (XHTML-like markup).
    This is what Confluence renders natively.
    """
    quality_color = {"high": "Green", "medium": "Yellow", "low": "Red"}.get(overall_quality, "Yellow")

    lines = []

    # ── Info panel (status macro) ─────────────────────────────────
    lines.append(
        f'<ac:structured-macro ac:name="info">'
        f'<ac:rich-text-body>'
        f'<p><strong>Incident:</strong> {incident_id} &nbsp;|&nbsp; '
        f'<strong>Severity:</strong> {severity} &nbsp;|&nbsp; '
        f'<strong>CI:</strong> {ci} &nbsp;|&nbsp; '
        f'<strong>MTTR:</strong> {mttr_minutes} min &nbsp;|&nbsp; '
        f'<strong>Team:</strong> {team}</p>'
        f'<p><strong>Opened:</strong> {opened_at} &nbsp;|&nbsp; '
        f'<strong>Closed:</strong> {closed_at} &nbsp;|&nbsp; '
        f'<strong>Quality:</strong> '
        f'<ac:structured-macro ac:name="status">'
        f'<ac:parameter ac:name="colour">{quality_color}</ac:parameter>'
        f'<ac:parameter ac:name="title">{overall_quality.upper()} ({quality_score}/100)</ac:parameter>'
        f'</ac:structured-macro></p>'
        f'</ac:rich-text-body></ac:structured-macro>'
    )

    # ── Sections ──────────────────────────────────────────────────
    import html as _html
    for section in result.sections:
        safe_heading = _html.escape(section.heading)
        lines.append(f"<h2>{safe_heading}</h2>")
        # Wrap each paragraph (split by double newline)
        for para in section.content.split("\n\n"):
            para = para.strip()
            if para:
                safe_para = _html.escape(para)
                lines.append(f"<p>{safe_para}</p>")

    # ── Action items table ────────────────────────────────────────
    if result.action_items:
        lines.append("<h2>Action items</h2>")
        lines.append(
            '<table><thead><tr>'
            '<th>Owner</th><th>Task</th><th>Due</th><th>Status</th>'
            '</tr></thead><tbody>'
        )
        for item in result.action_items:
            lines.append(
                f"<tr><td>{_html.escape(item.owner)}</td><td>{_html.escape(item.task)}</td>"
                f"<td>{_html.escape(item.due)}</td>"
                f'<td><ac:structured-macro ac:name="status">'
                f'<ac:parameter ac:name="colour">Yellow</ac:parameter>'
                f'<ac:parameter ac:name="title">Open</ac:parameter>'
                f'</ac:structured-macro></td></tr>'
            )
        lines.append("</tbody></table>")

    # ── Tags / labels note ────────────────────────────────────────
    if result.tags:
        tag_str = "  ".join(result.tags)
        lines.append(f"<p><em>Labels: {tag_str}</em></p>")

    # ── Footer ────────────────────────────────────────────────────
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append(f'<p><em>Generated by RCA Agent on {ts}</em></p>')

    return "\n".join(lines)


# ── Public API ────────────────────────────────────────────────────

async def create_postmortem_page(
    result: ConfluenceResult,
    incident_id: str,
    severity: str,
    ci: str,
    mttr_minutes: int = 0,
    quality_score: int = 0,
    overall_quality: str = "medium",
    opened_at: str = "",
    closed_at: str = "",
    team: str = "",
) -> dict:
    """
    Create a Confluence page for the post-mortem.
    Returns a dict with: page_id, page_url, title, space_key
    """
    if not CONF_BASE_URL:
        raise RuntimeError("Confluence not initialised — call init_confluence() first")

    storage_body = _build_confluence_storage(
        result, incident_id, severity, ci,
        mttr_minutes, quality_score, overall_quality,
        opened_at, closed_at, team,
    )

    # Sanitize tags: Confluence labels can't have spaces, colons, or special chars
    def _sanitize_label(tag: str) -> str:
        import re
        # Remove everything after colon (e.g. "incident severity: P3" -> "P3")
        if ":" in tag:
            tag = tag.split(":")[-1]
        # Replace spaces/special chars with hyphens, lowercase
        tag = re.sub(r"[^a-z0-9\-]", "-", tag.lower().strip())
        tag = re.sub(r"-+", "-", tag).strip("-")
        return tag[:255] if tag else "rca"

    clean_tags = [_sanitize_label(t) for t in result.tags if t]

    payload = {
        "type":  "page",
        "title": result.page_title,
        "space": {"key": CONF_SPACE_KEY},
        "ancestors": [{"id": str(CONF_PARENT_PAGE_ID)}] if CONF_PARENT_PAGE_ID else [],
        "body": {
            "storage": {
                "value":          storage_body,
                "representation": "storage",
            }
        },
    }

    log.info(
        "Creating Confluence page  title=%s  space=%s  parent=%s",
        result.page_title, CONF_SPACE_KEY, CONF_PARENT_PAGE_ID,
    )

    async with httpx.AsyncClient(auth=_auth(), headers=_headers(), timeout=CONF_TIMEOUT) as client:
        resp = await client.post(
            f"{CONF_BASE_URL}/rest/api/content",
            json=payload,
        )

        if not resp.is_success:
            log.error(
                "Confluence page creation failed  status=%s  body=%s",
                resp.status_code, resp.text[:500],
            )
            resp.raise_for_status()

        data    = resp.json()
        page_id = data.get("id", "")
        page_url = (
            f"{CONF_BASE_URL}{data.get('_links', {}).get('webui', '')}"
        )

        log.info("Confluence page created  id=%s  url=%s", page_id, page_url)

        # Add labels via separate API call (not supported in create payload for Cloud)
        if clean_tags and page_id:
            try:
                label_resp = await client.post(
                    f"{CONF_BASE_URL}/rest/api/content/{page_id}/label",
                    json=[{"prefix": "global", "name": t} for t in clean_tags],
                )
                if not label_resp.is_success:
                    log.warning("Labels could not be added: %s", label_resp.text[:200])
            except Exception as e:
                log.warning("Label post failed (non-critical): %s", e)

        return {
            "page_id":   page_id,
            "page_url":  page_url,
            "title":     result.page_title,
            "space_key": CONF_SPACE_KEY,
        }


async def page_exists(title: str) -> bool:
    """Check if a page with the given title already exists in the space."""
    async with httpx.AsyncClient(auth=_auth(), headers=_headers(), timeout=CONF_TIMEOUT) as client:
        resp = await client.get(
            f"{CONF_BASE_URL}/rest/api/content",
            params={
                "title":     title,
                "spaceKey":  CONF_SPACE_KEY,
                "type":      "page",
                "expand":    "version",
            },
        )
        if resp.is_success:
            results = resp.json().get("results", [])
            return len(results) > 0
    return False
