apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rca-frontend.fullname" . }}-config
  namespace: {{ include "rca-frontend.namespace" . }}
  labels:
    {{- include "rca-frontend.labels" . | nindent 4 }}
data:
  BACKEND_URL: {{ .Values.backendUrl | quote }}
