apiVersion: v1
kind: Service
metadata:
  name: {{ include "rca-frontend.fullname" . }}
  namespace: {{ include "rca-frontend.namespace" . }}
  labels:
    {{- include "rca-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rca-frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
