apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rca-backend.fullname" . }}-config
  namespace: {{ include "rca-backend.namespace" . }}
  labels:
    {{- include "rca-backend.labels" . | nindent 4 }}
data:
  GCP_PROJECT_ID: {{ .Values.gcp.projectId | quote }}
  GCP_LOCATION:   {{ .Values.gcp.location | quote }}
  GEMINI_MODEL:   {{ .Values.gcp.geminiModel | quote }}
  CORS_ORIGINS:   {{ .Values.corsOrigins | quote }}
